MatrixMap.exe /c Maps\demo1.cmap
MatrixMap.exe /c Maps\demo2.cmap
MatrixMap.exe /c Maps\terron.cmap
MatrixMap.exe /c Maps\training.cmap
MatrixMap.exe /c Maps\desert1_3e.cmap
MatrixMap.exe /c Maps\desert2_2e.cmap
MatrixMap.exe /c Maps\desert3_3e.cmap
MatrixMap.exe /c Maps\mars1_2e.cmap
MatrixMap.exe /c Maps\mars2_3e.cmap
MatrixMap.exe /c Maps\mars3_3e.cmap
MatrixMap.exe /c Maps\mars4_3e.cmap
MatrixMap.exe /c Maps\summer1_3e.cmap
MatrixMap.exe /c Maps\summer2_3e.cmap
MatrixMap.exe /c Maps\summer3_2e.cmap
MatrixMap.exe /c Maps\summer4_2e.cmap
MatrixMap.exe /c Maps\winter1_1e.cmap
MatrixMap.exe /c Maps\winter2_2e.cmap
MatrixMap.exe /c Maps\winter3_3e.cmap
MatrixMap.exe /c Maps\winter4_2e.cmap
MatrixMap.exe /c Maps\winter5_3e.cmap
